version: '3.8'

services:
  frontend:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    networks:
      - pet-network
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - pet-network
    depends_on:
      - db

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: pet_tips
    volumes:
      - pet-db-data:/var/lib/mysql
    networks:
      - pet-network

volumes:
  pet-db-data:

networks:
  pet-network:

